spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:h2:mem:class_registration_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:class_admin}
spring.datasource.password=${DB_PASSWORD:yourpassword}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# Tell Spring where to find JSP files
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Disable Thymeleaf if it was added by default
spring.thymeleaf.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging.level.org.springframework.security=${LOG_LEVEL_SECURITY:INFO}
logging.level.org.springframework.web=${LOG_LEVEL_WEB:INFO}
logging.level.org.springframework.web.servlet.DispatcherServlet=${LOG_LEVEL_WEBMVC:INFO}

# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:julia.thao.003@gmail.com}
spring.mail.password=${MAIL_PASSWORD:habgzexqunwgaehr}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED:true}