spring.datasource.url=jdbc:postgresql://localhost:5432/class_registration_db
spring.datasource.username=class_admin
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Tell Spring where to find JSP files
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Disable Thymeleaf if it was added by default
spring.thymeleaf.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging.level.org.springframework.security=DEBUG

# ── Email Configuration ───────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=julia.thao.003@gmail.com
spring.mail.password=zsca ngjw uzie citm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true